"use client";

import { useMemo, useState } from "react";
import { ArrowLeft, ArrowUpRight, Download, Filter, Search } from "lucide-react";
import { BRAND, PLATFORMS, PRODUCTS, SOURCES, STORES, dateOffset, sum, type Campaign, type Daily, type Source } from "@/lib/demo-data";
import { Bars, Card, Chart, DataTable, Kpis, Tabs, fmt, type AppContext, type Screen } from "@/components/demo-app";

const compare = (n: number) => fmt.pct(5 + n % 14);
function heading(title: string, subtitle: string, actions?: React.ReactNode) { return <div className="ref-page-head"><div><h1>{title}</h1><p>{subtitle}</p></div>{actions}</div>; }
function byStore(rows: Daily[]) { return STORES.map(store => ({ store, ...sum(rows.filter(row => row.storeId === store.id)) })).filter(row => row.orders > 0); }
function series(rows: Daily[], field: "sales" | "orders" | "adSpend" | "attributedRevenue") { const dates = [...new Set(rows.map(row => row.date))].sort(); return dates.map(date => rows.filter(row => row.date === date).reduce((n, row) => n + row[field], 0)); }
function bySource(rows: Daily[], metric: "sales" | "orders") { return SOURCES.map(source => ({ source, value: rows.reduce((n, row) => n + row.bySource[source][metric], 0) })); }
function ProductTable({ rows }: { rows: Daily[] }) { const total = sum(rows); return <DataTable headers={["Product", "Category", "Units", "Revenue", "Est. margin"]} rows={PRODUCTS.map((p, i) => { const units = Math.round(total.orders * (0.24 - i * 0.016)); return [p.name, p.category, fmt.number(units), fmt.money(units * p.price), `${Math.round(p.margin * 100)}%`]; })}/>; }
function StoreButtons({ rows, setStoreId }: { rows: Daily[]; setStoreId: (id: string) => void }) { return <DataTable headers={["Store", "Net sales", "Orders", "Ad spend", "Attributed revenue", "ROAS"]} rows={byStore(rows).sort((a,b)=>b.roas-a.roas).map(r=>[r.store.name,fmt.money(r.sales),fmt.number(r.orders),fmt.money(r.adSpend),fmt.money(r.attributedRevenue),`${fmt.decimal(r.roas)}×`])} onRow={index=>setStoreId(byStore(rows).sort((a,b)=>b.roas-a.roas)[index].store.id)}/>; }
function Dashboard({ context }: { context: AppContext }) {
  const { rows, storeId, setStoreId, demo } = context; const total = sum(rows);
  const ranked = byStore(rows).filter(row=>row.adSpend>0).sort((a,b)=>b.roas-a.roas);
  const selected = STORES.find(store => store.id === storeId);
  const [detail, setDetail] = useState("overview");
  const top = ranked.slice(0,5); const bottom = ranked.slice(-5).reverse();
  const revenue = series(rows,"attributedRevenue"); const spend = series(rows,"adSpend");
  return <>{heading("Dashboard", selected ? `${selected.name} · POS-attributed store ROAS vs 6× target` : "POS-attributed ROAS by location · 6× target", <span className="ref-status">● All sources reporting</span>)}
    <div className="ref-quality">POS sales include completed business days through {demo.anchor}. Attribution values are simulated and follow the selected date range.</div>
    <Kpis values={[{label:"Gross sales",value:fmt.money(total.sales*1.08),sub:compare(total.orders)},{label:"Net sales",value:fmt.money(total.sales),sub:compare(total.sales)},{label:"Total orders",value:fmt.number(total.orders),sub:compare(total.orders)},{label:"Average order value",value:fmt.money(total.aov),sub:"Net sales ÷ orders"},{label:"Attributed sales",value:fmt.money(total.attributedRevenue),sub:"Mapped campaign orders"},{label:"Attributed orders",value:fmt.number(total.attributedOrders),sub:"POS matched"},{label:"Ad spend",value:fmt.money(total.adSpend),sub:"Google + Meta + TikTok"},{label:"Attributed ROAS",value:`${fmt.decimal(total.roas)}×`,sub:`vs ${BRAND.targetRoas}× target`,tone:total.roas>=6?"good":"watch"}]}/>
    <Tabs value={detail} setValue={setDetail} options={[{id:"overview",label:"Overview"},{id:"stores",label:"Per-Store ROAS"},{id:"orders",label:"Attributed Orders"}]}/>
    {detail==="overview" ? <><div className="ref-grid two"><Card title="Daily Ad Spend & Attributed Revenue" sub="Completed business days · POS matched"><Chart values={revenue} compare={spend.map(n=>n*6)} color="#f97316"/><div className="ref-legend"><i style={{background:"#f97316"}}/>Attributed revenue <i style={{background:"#9bb4eb"}}/>Ad spend × 6</div></Card><Card title="Google vs Meta" sub="Spend, attributed revenue and efficiency"><DataTable headers={["Channel","Spend","Revenue","ROAS"]} rows={PLATFORMS.map((p,i)=>[p,fmt.money(total.adSpend*[.48,.36,.16][i]),fmt.money(total.attributedRevenue*[.52,.36,.12][i]),`${(total.roas*[1.08,1,.75][i]).toFixed(2)}×`])}/><div className="ref-mini-title">Customer Acquisition by Channel</div><Bars values={PLATFORMS.map((p,i)=>({label:p,value:Math.round(total.newCustomers*[.48,.35,.17][i]),display:fmt.number(Math.round(total.newCustomers*[.48,.35,.17][i]))}))}/></Card></div>
      <div className="ref-grid two"><Card title="Top 5 Stores" sub="Highest ROAS · stores with spend"><Bars values={top.map(r=>({label:r.store.name,value:r.roas,display:`${fmt.decimal(r.roas)}×`}))} color="#16a34a"/></Card><Card title="Bottom 5 Stores" sub="Lowest ROAS · flagged for attention"><Bars values={bottom.map(r=>({label:r.store.name,value:r.roas,display:`${fmt.decimal(r.roas)}×`}))} color="#f97316"/></Card></div>
      <div className="ref-grid two"><Card title="Sales by Day-Part" sub="POS gross sales"><Bars values={["Breakfast","Lunch","Afternoon","Dinner","Late night"].map((label,i)=>({label,value:total.sales*[.06,.25,.14,.44,.11][i],display:fmt.money(total.sales*[.06,.25,.14,.44,.11][i])}))} color="#6366f1"/></Card><Card title="Order Sources" sub="Net sales by order channel"><Bars values={bySource(rows,"sales").map(s=>({label:s.source,value:s.value,display:fmt.money(s.value)}))} color="#0891b2"/></Card></div>
      <div className="ref-grid two"><Card title="Orders by Hour" sub="Peak order times across selected stores"><Chart values={[6,4,3,5,9,18,25,21,13,12,19,30,42,48,37,24,17,10]}/></Card><Card title="Customer Mix" sub="New vs returning · POS customer identity"><Bars values={[{label:"New",value:total.newCustomers,display:fmt.number(total.newCustomers)},{label:"Returning",value:total.returningCustomers,display:fmt.number(total.returningCustomers)}]} color="#16a34a"/></Card></div>
      <Card title="Top Products" sub="Ranked by modeled item revenue"><ProductTable rows={rows}/></Card><Card title="Per-Store ROAS" sub="Select a store to filter the dashboard"><StoreButtons rows={rows} setStoreId={setStoreId}/></Card></> : detail==="stores" ? <Card title="Per-Store ROAS" sub="Click a row to scope the dashboard"><StoreButtons rows={rows} setStoreId={setStoreId}/></Card> : <Card title="Attributed Orders" sub="Demo order details · campaign mapped"><DataTable headers={["Order","Store","Source","Campaign token","Revenue","Date"]} rows={rows.slice(-60).reverse().map((r,i)=>[`NS-${String(i+1).padStart(6,"0")}`,STORES.find(s=>s.id===r.storeId)?.name||"—",SOURCES[i%5],`NS-${i%2?"META":"GADS"}-${r.storeId.slice(-3)}`,fmt.money(r.sales/r.orders),r.date])}/></Card>}</>;
}

function SalesComparison({context}:{context:AppContext}) {
  const [mode,setMode]=useState("Daily"); const [sort,setSort]=useState("sales"); const [descending,setDescending]=useState(true);
  const cutoff = mode==="Daily"?1:mode==="Weekly"?7:mode==="Monthly"?30:Math.min(90,Number(context.period));
  const current = context.rows.filter(r=>r.date>=dateOffset(context.demo.anchor, 1-cutoff));
  const rows = byStore(current);
  rows.sort((a,b)=>{const x=sort==="orders"?a.orders:sort==="aov"?a.aov:a.sales;const y=sort==="orders"?b.orders:sort==="aov"?b.aov:b.sales;return descending?y-x:x-y;});
  return <>{heading("Sales Comparison", "Sales Comparison Report · current period vs previous period and last year")}<div className="ref-toolbar"><Tabs value={mode} setValue={setMode} options={["Daily","Weekly","Monthly","Custom"].map(x=>({id:x,label:x}))}/><div className="ref-toolbar-right"><span>Through {context.demo.anchor}</span><select aria-label="Sort sales comparison" value={sort} onChange={e=>setSort(e.target.value)}><option value="sales">Sort: Net sales</option><option value="orders">Sort: Orders</option><option value="aov">Sort: AOV</option></select><button onClick={()=>setDescending(!descending)}>{descending?"↓ Desc":"↑ Asc"}</button></div></div>
    <Card title="Sales Comparison Report" sub={`${rows.length} locations · ${mode.toLowerCase()} comparison · click store to filter`}><DataTable headers={["Store","CURRENT $","CURRENT #","CURRENT AVG","PREVIOUS $","PREVIOUS #","DIFF $","DIFF $%","LAST YEAR $","LY DIFF $%"]} rows={rows.map((r,i)=>[r.store.name,fmt.money(r.sales),fmt.number(r.orders),fmt.money(r.aov),fmt.money(r.sales/(1.04+i%5*.01)),fmt.number(r.orders/(1.04+i%5*.01)),fmt.money(r.sales-r.sales/(1.04+i%5*.01)),fmt.pct(4+i%5),fmt.money(r.sales/(1.07+i%6*.01)),fmt.pct(7+i%6)])} onRow={i=>{context.setStoreId(rows[i].store.id);context.setScreen("store-roas");}}/></Card><p className="ref-footnote">Previous and last-year columns are modeled comparison periods for this demo.</p></>;
}

function SourceComparison({context}:{context:AppContext}) {
  const [metric,setMetric]=useState<"sales"|"orders">("sales"); const [enabled,setEnabled]=useState<Source[]>(SOURCES);
  const [sort,setSort]=useState("store");
  const items = byStore(context.rows).sort((a,b)=>sort==="sales"?b.sales-a.sales:sort==="orders"?b.orders-a.orders:a.store.name.localeCompare(b.store.name));
  const val=(rows:Daily[],source:Source)=>rows.reduce((n,r)=>n+r.bySource[source][metric],0);
  const cell=(value:number)=>metric==="sales"?fmt.money(value):fmt.number(value);
  return <>{heading("Source Comparison","Order Source Comparison by Location · first-party and marketplace channels")}<div className="ref-toolbar"><Tabs value={metric} setValue={x=>setMetric(x as "sales"|"orders")} options={[{id:"sales",label:"Net Sales"},{id:"orders",label:"Order Count"}]}/><div className="ref-toolbar-right"><Filter size={14}/><span>Sources</span>{SOURCES.map(source=><label className="ref-check" key={source}><input type="checkbox" checked={enabled.includes(source)} onChange={()=>setEnabled(enabled.includes(source)?enabled.filter(x=>x!==source):[...enabled,source])}/>{source}</label>)}<select aria-label="Sort source comparison" value={sort} onChange={e=>setSort(e.target.value)}><option value="store">Store A–Z</option><option value="sales">Sales</option><option value="orders">Orders</option></select></div></div>
    <Card title="Order Source Comparison by Location" sub="All Sources totals only checked channels"><DataTable headers={["Store",...enabled,"All Sources"]} rows={items.map(item=>{const storeRows=context.rows.filter(r=>r.storeId===item.store.id);return [item.store.name,...enabled.map(source=>cell(val(storeRows,source))),cell(enabled.reduce((n,source)=>n+val(storeRows,source),0))]})} onRow={i=>{context.setStoreId(items[i].store.id);context.setScreen("store-roas");}}/></Card></>;
}

function PosAnalysis({context}:{context:AppContext}) {
  const [tab,setTab]=useState("dashboard"); const total=sum(context.rows); const stores=byStore(context.rows); const values=series(context.rows,"sales");
  return <>{heading("POS Analysis",`Northstar POS · ${context.storeId==="all"?"All stores":STORES.find(s=>s.id===context.storeId)?.name}`)}<Tabs value={tab} setValue={setTab} options={[{id:"dashboard",label:"Dashboard"},{id:"customers",label:"Customers"},{id:"comparison",label:"Store Comparison"},{id:"firstparty",label:"First-Party vs Third-Party"}]}/>
    {tab==="dashboard"?<><Kpis values={[{label:"Net sales",value:fmt.money(total.sales),sub:compare(total.orders)},{label:"Orders",value:fmt.number(total.orders),sub:compare(total.sales)},{label:"Average order value",value:fmt.money(total.aov),sub:"Net sales ÷ orders"},{label:"Unique customers",value:fmt.number(total.newCustomers+total.returningCustomers),sub:"Modeled customers"}]}/><div className="ref-grid two"><Card title="Revenue & Orders Over Time" sub="Completed business days"><Chart values={values} compare={series(context.rows,"orders").map(x=>x*total.aov)}/></Card><Card title="Order Sources" sub="Net sales by source"><Bars values={bySource(context.rows,"sales").map(x=>({label:x.source,value:x.value,display:fmt.money(x.value)}))}/></Card></div><div className="ref-grid two"><Card title="Revenue & Orders by Daypart"><Bars values={["Breakfast","Lunch","Afternoon","Dinner","Late Night"].map((label,i)=>({label,value:total.sales*[.06,.25,.14,.44,.11][i],display:fmt.money(total.sales*[.06,.25,.14,.44,.11][i])}))} color="#16a34a"/></Card><Card title="Top 10 Products by Revenue"><ProductTable rows={context.rows}/></Card></div><Card title="Revenue by Location"><StoreButtons rows={context.rows} setStoreId={context.setStoreId}/></Card></>:null}
    {tab==="customers"?<><Kpis values={[{label:"New customers",value:fmt.number(total.newCustomers)},{label:"Returning customers",value:fmt.number(total.returningCustomers)},{label:"New customer share",value:`${Math.round(total.newCustomers/Math.max(1,total.newCustomers+total.returningCustomers)*100)}%`},{label:"Returning AOV",value:fmt.money(total.aov*1.08)}]}/><div className="ref-grid two"><Card title="New vs Returning Customers Over Time"><Chart values={series(context.rows,"orders").map(x=>x*.25)} compare={series(context.rows,"orders").map(x=>x*.56)} color="#16a34a"/></Card><Card title="Avg Order Value: New vs Returning"><Bars values={[{label:"New",value:total.aov*.94,display:fmt.money(total.aov*.94)},{label:"Returning",value:total.aov*1.08,display:fmt.money(total.aov*1.08)}]}/></Card></div><Card title="Top Customers" sub="Fictional customer segments · no personal data"><DataTable headers={["Segment","Customers","Orders","Net sales","AOV"]} rows={[["Frequent regulars",Math.round(total.returningCustomers*.24),fmt.number(total.orders*.21),fmt.money(total.sales*.27),fmt.money(total.aov*1.14)],["Repeat customers",Math.round(total.returningCustomers*.76),fmt.number(total.orders*.45),fmt.money(total.sales*.48),fmt.money(total.aov*1.05)],["New guests",total.newCustomers,fmt.number(total.orders*.34),fmt.money(total.sales*.25),fmt.money(total.aov*.94)]]}/></Card></>:null}
    {tab==="comparison"?<Card title={`Store Comparison (${stores.length})`} sub="Click any store for a focused view"><StoreButtons rows={context.rows} setStoreId={context.setStoreId}/></Card>:null}
    {tab==="firstparty"?<><Kpis values={[{label:"First-party sales",value:fmt.money(bySource(context.rows,"sales").slice(0,3).reduce((n,r)=>n+r.value,0))},{label:"Third-party sales",value:fmt.money(bySource(context.rows,"sales").slice(3).reduce((n,r)=>n+r.value,0))},{label:"First-party orders",value:fmt.number(bySource(context.rows,"orders").slice(0,3).reduce((n,r)=>n+r.value,0))},{label:"Third-party share",value:`${Math.round(bySource(context.rows,"orders").slice(3).reduce((n,r)=>n+r.value,0)/total.orders*100)}%`}]}/><div className="ref-grid two"><Card title="First-Party Sources"><Bars values={bySource(context.rows,"sales").slice(0,3).map(x=>({label:x.source,value:x.value,display:fmt.money(x.value)}))} color="#16a34a"/></Card><Card title="Third-Party Marketplaces"><Bars values={bySource(context.rows,"sales").slice(3).map(x=>({label:x.source,value:x.value,display:fmt.money(x.value)}))} color="#f97316"/></Card></div><Card title="First-Party by Store"><StoreButtons rows={context.rows} setStoreId={context.setStoreId}/></Card></>:null}</>;
}

const plays = [
  { id:"reactivation", label:"Reactivation", action:"Win-back campaign", description:"One-time buyers with no recent repeat order" },
  { id:"lapsed", label:"Lapsed loyalists", action:"High-value win-back", description:"Previously loyal guests whose ordering has slowed" },
  { id:"direct", label:"Direct ordering push", action:"Own-channel creative", description:"Stores over-indexing on marketplaces" },
  { id:"reviews", label:"Review drive", action:"Leave-a-review incentive", description:"Stores trailing the local review benchmark" },
  { id:"soft", label:"Soft day + daypart", action:"Timed offer", description:"Underused time slots with capacity to grow" },
  { id:"combo", label:"Combo upsell", action:"Bundle on peak day", description:"High attach-rate product pairings" },
  { id:"loyalty", label:"Loyalty conversion", action:"Sign-up push", description:"Strong guest demand with low rewards enrollment" },
];
function Insights({context}:{context:AppContext}) {
  const [tab,setTab]=useState("overview");const [store,setStore]=useState(context.storeId==="all"?STORES[0].id:context.storeId);
  const selected=STORES.find(s=>s.id===store)!;const rows=context.rows.filter(r=>r.storeId===store);const metrics=sum(rows);
  const priority=[
    {title:"Win back one-time customers",why:"Bring recent first-time guests back for another order.",value:fmt.number(metrics.newCustomers*.35),label:"to win back"},
    {title:"Move orders off delivery apps",why:"Direct channels protect margin on repeat purchases.",value:`${Math.round((rows.reduce((n,r)=>n+r.bySource["DoorDash"].sales+r.bySource["Uber Eats"].sales,0)/Math.max(1,metrics.sales))*100)}%`,label:"of revenue"},
    {title:"Push your best combos",why:"Northern Lights Pizza with Cedar Smoke Wings lifts the check.",value:"+18%",label:"bigger orders"},
    {title:"Promote your slowest day",why:"Monday dinner has room for a timed offer.",value:"Mon",label:"quietest"},
  ];
  return <>{heading("Store Insights","Per-store deep dive with automatic findings and recommended actions",<select value={store} onChange={e=>setStore(e.target.value)} aria-label="Insight store">{STORES.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select>)}<Tabs value={tab} setValue={setTab} options={[{id:"overview",label:"Overview"},{id:"customers",label:"Customers"},{id:"channels",label:"Channels"},{id:"menu",label:"Basket & Menu"},{id:"local",label:"Local Market"}]}/><div className="ref-priority-grid">{priority.map((p,i)=><div className="ref-priority" key={p.title}><small>PRIORITY {i+1}</small><strong>{p.title}</strong><p>{p.why}</p><b>{p.value}</b><span>{p.label}</span></div>)}</div>
    <Kpis values={[{label:"Net sales",value:fmt.money(metrics.sales)},{label:"Orders",value:fmt.number(metrics.orders)},{label:"AOV",value:fmt.money(metrics.aov)},{label:"ROAS",value:`${fmt.decimal(metrics.roas)}×`}]}/>
    {tab==="overview"?<div className="ref-grid two"><Card title="Sales and Orders" sub={selected.name}><Chart values={series(rows,"sales")} compare={series(rows,"orders").map(x=>x*metrics.aov)} /></Card><Card title="Opportunity summary"><Bars values={priority.map((p,i)=>({label:p.title,value:4-i,display:p.value}))} color="#8b5cf6"/></Card></div>:null}
    {tab==="customers"?<div className="ref-grid two"><Card title="Customer Frequency"><Bars values={[{label:"One-time",value:metrics.newCustomers*.35},{label:"Repeat",value:metrics.returningCustomers*.6},{label:"Loyal",value:metrics.returningCustomers*.18}]}/></Card><Card title="New vs Returning"><Chart values={series(rows,"orders").map(x=>x*.25)} compare={series(rows,"orders").map(x=>x*.56)}/></Card></div>:null}
    {tab==="channels"?<div className="ref-grid two"><Card title="Revenue by Order Source"><Bars values={bySource(rows,"sales").map(r=>({label:r.source,value:r.value,display:fmt.money(r.value)}))}/></Card><Card title="First-Party vs Third-Party"><Bars values={[{label:"First-party",value:bySource(rows,"sales").slice(0,3).reduce((n,r)=>n+r.value,0)},{label:"Marketplace",value:bySource(rows,"sales").slice(3).reduce((n,r)=>n+r.value,0)}]}/></Card></div>:null}
    {tab==="menu"?<Card title="Top Products and Pairings"><ProductTable rows={rows}/></Card>:null}
    {tab==="local"?<div className="ref-grid two"><Card title="Review Position"><Kpis values={[{label:"Northstar rating",value:`${(4.1+(Number(store.slice(-2))%5)*.1).toFixed(1)}★`},{label:"Local median",value:"4.4★"}]}/></Card><Card title="Recommended local action"><p>Ask recent repeat guests to review {selected.name} after a completed order. Modeled local benchmark for demonstration.</p></Card></div>:null}</>;
}
function FleetStrategy({context}:{context:AppContext}) {
  const [active,setActive]=useState(plays[0].id);const [mode,setMode]=useState("One per store");const play=plays.find(p=>p.id===active)!;const stores=byStore(context.rows);
  const ranked=stores.map((r,i)=>({...r,score:Math.round(100-(i*17+plays.findIndex(p=>p.id===active)*11)%82)})).sort((a,b)=>b.score-a.score);
  return <>{heading("Fleet Strategy","Segment stores by opportunity and act on the group")}<div className="ref-toolbar"><Tabs value={mode} setValue={setMode} options={["One per store","All plays"].map(label=>({id:label,label}))}/><span>Stores scored against the fleet median</span></div><div className="ref-play-grid">{plays.map(p=><button className={active===p.id?"active":""} key={p.id} onClick={()=>setActive(p.id)}><span>{p.label}</span><strong>{Math.round(stores.length*(.33+plays.indexOf(p)*.035))}</strong><small>{p.action}</small></button>)}</div><div className="ref-grid two"><Card title={play.label} sub={play.description}><p className="ref-body-copy">Recommended play: <strong>{play.action}</strong>. Scores compare each store with the selected fleet. This demo uses modeled guest and sales signals.</p><Kpis values={[{label:"Qualified stores",value:fmt.number(Math.round(stores.length*.48))},{label:"Average opportunity",value:"High"},{label:"Top store",value:ranked[0]?.store.name||"—"}]}/></Card><Card title="Opportunity by Store"><Bars values={ranked.slice(0,6).map(r=>({label:r.store.name,value:r.score,display:`${r.score} pts`}))} color="#6366f1"/></Card></div><Card title="Fleet Rankings" sub="Click a store to inspect its dashboard"><DataTable headers={["Store","Region","Net sales","Orders","ROAS","Opportunity score","Recommended play"]} rows={ranked.map(r=>[r.store.name,r.store.region,fmt.money(r.sales),fmt.number(r.orders),`${fmt.decimal(r.roas)}×`,r.score,play.label])} onRow={i=>{context.setStoreId(ranked[i].store.id);context.setScreen("store-roas");}}/></Card></>;
}
function ReportBuilder({context}:{context:AppContext}) {
  const [sections,setSections]=useState(["Executive summary","Average order value","Paid media","First-party vs third-party revenue","Store performance","What campaign orders contain","Customers and loyalty"]);
  const [notes,setNotes]=useState("");const [title,setTitle]=useState("Northstar Slice Co. · Performance Review");const [preview,setPreview]=useState(false);const total=sum(context.rows);
  const choices=["Executive summary","Average order value","Paid media","First-party vs third-party revenue","Store performance","What campaign orders contain","Google conversion actions","Creative shipped this period","Customers and loyalty","Platform optimisations"];
  const renderSection=(section:string)=>{
    if(section==="Executive summary")return <p>The selected stores generated {fmt.money(total.sales)} in net sales from {fmt.number(total.orders)} orders at {fmt.decimal(total.roas)}× attributed ROAS.</p>;
    if(section==="Average order value")return <p>Average order value was {fmt.money(total.aov)} across the selected period ({fmt.money(total.sales)} ÷ {fmt.number(total.orders)} orders).</p>;
    if(section==="Paid media")return <p>Modeled spend of {fmt.money(total.adSpend)} generated {fmt.money(total.attributedRevenue)} in attributed sales and {fmt.number(total.attributedOrders)} attributed orders.</p>;
    if(section==="First-party vs third-party revenue"){
      const first=bySource(context.rows,"sales").filter(r=>["In Store","Web","Mobile App"].includes(r.source)).reduce((n,r)=>n+r.value,0);
      return <p>First-party channels generated {fmt.money(first)} ({(first/Math.max(1,total.sales)*100).toFixed(1)}% of net sales); marketplaces generated {fmt.money(total.sales-first)}.</p>;
    }
    if(section==="Store performance")return <DataTable headers={["Store","Net sales","Orders","ROAS"]} rows={byStore(context.rows).sort((a,b)=>b.sales-a.sales).slice(0,5).map(r=>[r.store.name,fmt.money(r.sales),fmt.number(r.orders),`${fmt.decimal(r.roas)}×`])}/>;
    if(section==="What campaign orders contain")return <p>Featured items in attributed orders: {PRODUCTS.slice(0,3).map(p=>p.name).join(", ")}. Product mix is modeled from the selected store and date range.</p>;
    if(section==="Google conversion actions")return <DataTable headers={["Action","Conversions","Mode"]} rows={[["Purchase",fmt.number(total.attributedOrders*.48),"Demo"],["Add to cart",fmt.number(total.attributedOrders*.74),"Demo"],["Begin checkout",fmt.number(total.attributedOrders*.61),"Demo"]]}/>;
    if(section==="Creative shipped this period")return <p>Family Table, Friday Slice, and Order Direct are fictional campaign creatives used in the paid-media demo.</p>;
    if(section==="Customers and loyalty")return <p>{fmt.number(total.newCustomers)} new customers and {fmt.number(total.returningCustomers)} returning-customer orders were modeled for the selected period.</p>;
    return <p>Review under-target locations against the {BRAND.targetRoas}× ROAS goal, then test direct ordering and weekend offers with the relevant store teams.</p>;
  };
  return <>{heading("Report Builder","Build and export a fictional Northstar performance review",<button className="ref-primary" onClick={()=>setPreview(!preview)}>{preview?"Edit report":"Preview report"} <ArrowUpRight size={14}/></button>)}{!preview?<div className="ref-grid report-grid"><Card title="Report sections" sub="Choose the sections to include"><div className="ref-section-choices">{choices.map(choice=><label key={choice}><input type="checkbox" checked={sections.includes(choice)} onChange={()=>setSections(sections.includes(choice)?sections.filter(x=>x!==choice):[...sections,choice])}/>{choice}</label>)}</div></Card><Card title="Report options"><label className="ref-field">Report title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="ref-field">Account team notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Add notes for the demo presentation"/></label><p className="ref-footnote">The report uses the current store and date filters.</p></Card></div>:<div className="ref-report-preview"><div className="ref-report-top"><span>METRIXMATE · DEMO REPORT</span><button onClick={()=>window.print()}><Download size={14}/> Print or save PDF</button></div><h1>{title.trim()||"Performance Review"}</h1><p>Reporting through {context.demo.anchor} · {context.storeId==="all"?"All stores":STORES.find(s=>s.id===context.storeId)?.name}</p>{sections.map(section=><section key={section}><h2>{section}</h2>{renderSection(section)}</section>)}{notes&&<section><h2>Account team notes</h2><p>{notes}</p></section>}</div>}</>;
}
function PaidMedia({context,platform}:{context:AppContext;platform:"Meta Ads"|"Google Ads"|"TikTok Ads"}) {
  const [view,setView]=useState("Table");const [detailId,setDetailId]=useState<string|null>(null);const [status,setStatus]=useState("All statuses");
  const platformShare = [0.48,0.36,0.16][PLATFORMS.indexOf(platform)];
  const selectedShare = context.selectedPlatform === "all" ? platformShare : context.selectedPlatform === platform ? 1 : 0;
  const campaigns=context.demo.campaigns.filter(c=>c.platform===platform&&(context.storeId==="all"||c.storeId===context.storeId)&&(status==="All statuses"||c.status===status)).map(c=>{
    const selectedSpend=context.rows.filter(row=>row.storeId===c.storeId).reduce((n,row)=>n+row.adSpend,0)*selectedShare;
    const factor=c.spend?selectedSpend/c.spend:0;
    return {...c,spend:selectedSpend,impressions:Math.round(c.impressions*factor),clicks:Math.round(c.clicks*factor),orders:Math.round(c.orders*factor),revenue:c.revenue*factor};
  });
  const detail=campaigns.find(c=>c.id===detailId)||null;
  const total=campaigns.reduce((a,c)=>({spend:a.spend+c.spend,impressions:a.impressions+c.impressions,clicks:a.clicks+c.clicks,orders:a.orders+c.orders,revenue:a.revenue+c.revenue}),{spend:0,impressions:0,clicks:0,orders:0,revenue:0});
  if(detail)return <><button className="ref-back" onClick={()=>setDetailId(null)}><ArrowLeft size={14}/> Back to {platform}</button>{heading("Campaign Detail",detail.name)}<Kpis values={[{label:"Ad Spend",value:fmt.money(detail.spend)},{label:"Impressions",value:fmt.number(detail.impressions)},{label:"Clicks",value:fmt.number(detail.clicks)},{label:"ROAS",value:`${fmt.decimal(detail.revenue/detail.spend)}×`}]}/><div className="ref-grid two"><Card title="Campaign performance" sub={detail.objective}><Chart values={[34,45,39,51,48,57,64,61,69,72,78,82]} color={platform==="Meta Ads"?"#1877f2":"#4285f4"}/></Card><Card title="Ad set performance"><DataTable headers={["Ad set","Spend","Impressions","Clicks","Orders"]} rows={["Local prospecting","Returning guests","Weekend offer"].map((x,i)=>[x,fmt.money(detail.spend*[.45,.32,.23][i]),fmt.number(detail.impressions*[.45,.32,.23][i]),fmt.number(detail.clicks*[.45,.32,.23][i]),fmt.number(detail.orders*[.45,.32,.23][i])])}/></Card></div><Card title="Ads" sub="Fictional creatives"><DataTable headers={["Ad","Delivery","Spend","Clicks","Attributed revenue"]} rows={["Family Table","Friday Slice","Order Direct"].map((x,i)=>[x,detail.status,fmt.money(detail.spend*[.42,.33,.25][i]),fmt.number(detail.clicks*[.42,.33,.25][i]),fmt.money(detail.revenue*[.42,.33,.25][i])])}/></Card></>;
  return <>{heading(platform==="TikTok Ads"?"TikTok Ads Analytics":platform==="Meta Ads"?"Meta Ads Analytics":"Google Ads Analytics",`${platform} performance · fictional account`)}<Kpis values={[{label:"Ad Spend",value:fmt.money(total.spend)},{label:"Impressions",value:fmt.compact(total.impressions)},{label:"Clicks",value:fmt.number(total.clicks)},{label:"CTR",value:`${(total.clicks/Math.max(1,total.impressions)*100).toFixed(2)}%`},{label:"Attributed orders",value:fmt.number(total.orders)},{label:"Attributed revenue",value:fmt.money(total.revenue)},{label:"ROAS",value:`${fmt.decimal(total.revenue/Math.max(1,total.spend))}×`},{label:"Active campaigns",value:fmt.number(campaigns.filter(c=>c.status==="Active").length)}]}/><div className="ref-grid two"><Card title="Spend & Revenue Over Time" sub="Modeled campaign results"><Chart values={series(context.rows,"attributedRevenue").map(x=>x*platformShare)} compare={series(context.rows,"adSpend").map(x=>x*platformShare*6)} color={platform==="Meta Ads"?"#1877f2":platform==="Google Ads"?"#4285f4":"#111827"}/></Card><Card title="Spend by Objective"><Bars values={[{label:"Sales",value:total.spend*.73,display:fmt.money(total.spend*.73)},{label:"Awareness",value:total.spend*.18,display:fmt.money(total.spend*.18)},{label:"Engagement",value:total.spend*.09,display:fmt.money(total.spend*.09)}]}/></Card></div><div className="ref-toolbar"><Tabs value={view} setValue={setView} options={[{id:"Table",label:"Campaign table"},{id:"Cards",label:"Campaign cards"}]}/><select value={status} onChange={e=>setStatus(e.target.value)} aria-label="Campaign status"><option>All statuses</option><option>Active</option><option>Paused</option></select></div><Card title={`${platform} Performance`} sub={`${campaigns.length} campaigns · select one for details`}>{view==="Table"?<DataTable headers={["Campaign","Status","Objective","Ad Spend","Impressions","Clicks","Orders","Revenue","ROAS"]} rows={campaigns.map(c=>[c.name,c.status,c.objective,fmt.money(c.spend),fmt.number(c.impressions),fmt.number(c.clicks),fmt.number(c.orders),fmt.money(c.revenue),`${fmt.decimal(c.revenue/c.spend)}×`])} onRow={i=>setDetailId(campaigns[i].id)}/>:<div className="ref-campaign-grid">{campaigns.map(c=><button key={c.id} onClick={()=>setDetailId(c.id)}><span>{c.status}</span><strong>{c.name}</strong><div>Spend <b>{fmt.money(c.spend)}</b></div><div>ROAS <b>{fmt.decimal(c.revenue/c.spend)}×</b></div></button>)}</div>}</Card></>;
}
function Ga4({context}:{context:AppContext}) {
  const [tab,setTab]=useState("Acquisition");const total=sum(context.rows);const sessions=Math.round(total.orders*7.4);const users=Math.round(sessions*.67);
  return <>{heading("Web Analytics (GA4)","Website and app behavior · fictional analytics property")}<Tabs value={tab} setValue={setTab} options={["Acquisition","Engagement","Monetization","Geographic","Store Performance"].map(label=>({id:label,label}))}/>
    {tab==="Acquisition"?<><Kpis values={[{label:"Sessions",value:fmt.number(sessions)},{label:"Total users",value:fmt.number(users)},{label:"New users",value:fmt.number(users*.61)},{label:"Engaged sessions",value:fmt.number(sessions*.72)}]}/><div className="ref-grid two"><Card title="Sessions Over Time"><Chart values={series(context.rows,"orders").map(x=>x*7.4)}/></Card><Card title="Traffic Acquisition" sub="Session primary channel group"><Bars values={[{label:"Organic Search",value:sessions*.32},{label:"Paid Search",value:sessions*.28},{label:"Direct",value:sessions*.19},{label:"Paid Social",value:sessions*.13},{label:"Referral",value:sessions*.08}]}/></Card></div><Card title="Traffic Acquisition Detail"><DataTable headers={["Channel","Sessions","Users","Engagement rate","Orders"]} rows={["Organic Search","Paid Search","Direct","Paid Social","Referral"].map((label,i)=>[label,fmt.number(sessions*[.32,.28,.19,.13,.08][i]),fmt.number(users*[.32,.28,.19,.13,.08][i]),`${(69+i*2).toFixed(1)}%`,fmt.number(total.orders*[.32,.28,.19,.13,.08][i])])}/></Card></>:null}
    {tab==="Engagement"?<><Kpis values={[{label:"Engaged sessions",value:fmt.number(sessions*.72)},{label:"Engagement rate",value:"72.0%"},{label:"Avg engagement time",value:"1m 48s"},{label:"Events",value:fmt.number(sessions*4.6)}]}/><div className="ref-grid two"><Card title="Engagement Trend"><Chart values={series(context.rows,"orders").map(x=>x*5.2)}/></Card><Card title="Events by Name"><Bars values={[{label:"page_view",value:sessions*2.2},{label:"session_start",value:sessions},{label:"view_item",value:sessions*.7},{label:"add_to_cart",value:sessions*.25},{label:"purchase",value:total.orders}]}/></Card></div></>:null}
    {tab==="Monetization"?<><Kpis values={[{label:"Online revenue",value:fmt.money(total.sales*.52)},{label:"Orders",value:fmt.number(total.orders*.52)},{label:"Purchase rate",value:`${(total.orders/sessions*100).toFixed(1)}%`},{label:"AOV",value:fmt.money(total.aov)}]}/><div className="ref-grid two"><Card title="Online Revenue Trend"><Chart values={series(context.rows,"sales").map(x=>x*.52)}/></Card><Card title="Revenue by Source"><Bars values={bySource(context.rows,"sales").slice(1,3).map(r=>({label:r.source,value:r.value,display:fmt.money(r.value)}))}/></Card></div></>:null}
    {tab==="Geographic"?<><Kpis values={[{label:"Active markets",value:"5"},{label:"Total sessions",value:fmt.number(sessions)},{label:"Users",value:fmt.number(users)},{label:"Online revenue",value:fmt.money(total.sales*.52)}]}/><Card title="Geographic Performance" sub="Northstar demo regions"><DataTable headers={["Region","Stores","Sessions","Users","Orders","Net sales"]} rows={["Great Lakes","Northeast","Prairie","Pacific Northwest","Ontario"].map(region=>{const r=context.rows.filter(row=>STORES.find(s=>s.id===row.storeId)?.region===region);const s=sum(r);return [region,STORES.filter(st=>st.region===region).length,fmt.number(s.orders*7.4),fmt.number(s.orders*4.9),fmt.number(s.orders),fmt.money(s.sales)];})}/></Card></>:null}
    {tab==="Store Performance"?<Card title="Store Performance" sub="Digital sessions and online sales"><DataTable headers={["Store","Sessions","Users","Online orders","Online sales","Conversion rate"]} rows={byStore(context.rows).map(r=>[r.store.name,fmt.number(r.orders*7.4),fmt.number(r.orders*4.9),fmt.number(r.orders*.52),fmt.money(r.sales*.52),"7.0%"])} onRow={i=>context.setStoreId(byStore(context.rows)[i].store.id)}/></Card>:null}</>;
}

export function AnalyticsScreen({screen,context}:{screen:Screen;context:AppContext}) {
  if(screen==="store-roas")return <Dashboard context={context}/>;
  if(screen==="sales-report")return <SalesComparison context={context}/>;
  if(screen==="source-comparison")return <SourceComparison context={context}/>;
  if(screen==="pos-insights")return <PosAnalysis context={context}/>;
  if(screen==="insights")return <Insights context={context}/>;
  if(screen==="fleet-strategy")return <FleetStrategy context={context}/>;
  if(screen==="report")return <ReportBuilder context={context}/>;
  if(screen==="meta")return <PaidMedia context={context} platform="Meta Ads"/>;
  if(screen==="google-ads")return <PaidMedia context={context} platform="Google Ads"/>;
  if(screen==="tiktok")return <PaidMedia context={context} platform="TikTok Ads"/>;
  return <Ga4 context={context}/>;
}
